/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AcceptedPaymentMethod } from './models/AcceptedPaymentMethod';
export type { AddressCompatibility } from './models/AddressCompatibility';
export type { AppConfig } from './models/AppConfig';
export type { AssetBackedCurrency } from './models/AssetBackedCurrency';
export type { AssetBalance } from './models/AssetBalance';
export type { AssetLock } from './models/AssetLock';
export type { AssetMarketData } from './models/AssetMarketData';
export type { BalanceDetail } from './models/BalanceDetail';
export type { BalanceMetric } from './models/BalanceMetric';
export { CardChargeCryptoRequestStatus } from './models/CardChargeCryptoRequestStatus';
export type { CartCheckoutCompatibilityRequest } from './models/CartCheckoutCompatibilityRequest';
export type { CartCheckoutCompatibilityResponse } from './models/CartCheckoutCompatibilityResponse';
export type { CartCheckoutRequest } from './models/CartCheckoutRequest';
export type { CartCreationCompatibilityRequest } from './models/CartCreationCompatibilityRequest';
export type { CartCreationCompatibilityResponse } from './models/CartCreationCompatibilityResponse';
export type { CartCreationRequest } from './models/CartCreationRequest';
export type { CartItemCompatibility } from './models/CartItemCompatibility';
export type { CartItemCompatibilityResponse } from './models/CartItemCompatibilityResponse';
export type { CartItemRequest } from './models/CartItemRequest';
export type { CartResponse } from './models/CartResponse';
export type { CartUpdateCompatibilityRequest } from './models/CartUpdateCompatibilityRequest';
export type { CartUpdateCompatibilityResponse } from './models/CartUpdateCompatibilityResponse';
export type { CartUpdateRequest } from './models/CartUpdateRequest';
export type { ChangePasswordRequest } from './models/ChangePasswordRequest';
export { CloudCartType } from './models/CloudCartType';
export { CloudCheckoutCurrency } from './models/CloudCheckoutCurrency';
export type { CloudFee } from './models/CloudFee';
export type { CreateListingRequest } from './models/CreateListingRequest';
export type { CryptocurrencyInfo } from './models/CryptocurrencyInfo';
export type { CurrencyAmount } from './models/CurrencyAmount';
export type { Customer } from './models/Customer';
export type { CustomerMarket } from './models/CustomerMarket';
export type { CustomerMarketItem } from './models/CustomerMarketItem';
export type { CustomerMarketListRequest } from './models/CustomerMarketListRequest';
export type { CustomerMarketListResponse } from './models/CustomerMarketListResponse';
export type { CustomerMarketSubscription } from './models/CustomerMarketSubscription';
export type { CustomerMarketSubscriptionPlan } from './models/CustomerMarketSubscriptionPlan';
export type { CustomerTradingPair } from './models/CustomerTradingPair';
export type { CustomerTradingPairAlert } from './models/CustomerTradingPairAlert';
export type { CustomerTradingPairItem } from './models/CustomerTradingPairItem';
export type { CustomerTradingPairRequest } from './models/CustomerTradingPairRequest';
export type { CustomerTradingPairResponse } from './models/CustomerTradingPairResponse';
export type { DepositCodeGenerationResponse } from './models/DepositCodeGenerationResponse';
export type { DepositCodeValidationDetails } from './models/DepositCodeValidationDetails';
export type { DepositCodeValidationResponse } from './models/DepositCodeValidationResponse';
export type { DepositMetadata } from './models/DepositMetadata';
export type { DepositMobileFeatures } from './models/DepositMobileFeatures';
export { DepositPaymentMethod } from './models/DepositPaymentMethod';
export type { DepositPreValidationRequest } from './models/DepositPreValidationRequest';
export type { DepositPreValidationResponse } from './models/DepositPreValidationResponse';
export type { DepositProcessingResponse } from './models/DepositProcessingResponse';
export type { DepositProcessingStatus } from './models/DepositProcessingStatus';
export type { DepositRequest } from './models/DepositRequest';
export type { DynamicUserCoin } from './models/DynamicUserCoin';
export type { EnhancedDepositResponse } from './models/EnhancedDepositResponse';
export type { EnhancedWalletResponse } from './models/EnhancedWalletResponse';
export type { EstimatedProfitProjection } from './models/EstimatedProfitProjection';
export { ExchangeRateVendor } from './models/ExchangeRateVendor';
export type { FacetValue } from './models/FacetValue';
export { FeeType } from './models/FeeType';
export type { FxRate } from './models/FxRate';
export type { Image } from './models/Image';
export type { Image2 } from './models/Image2';
export type { LedgerMarketExchangeRate } from './models/LedgerMarketExchangeRate';
export type { LimitResponse } from './models/LimitResponse';
export { ListingMessageType } from './models/ListingMessageType';
export { ListingPaymentMethod } from './models/ListingPaymentMethod';
export type { ListingSale } from './models/ListingSale';
export type { LockReference } from './models/LockReference';
export type { LockTimeline } from './models/LockTimeline';
export type { LoginRequest } from './models/LoginRequest';
export type { LoginResponse } from './models/LoginResponse';
export type { Market } from './models/Market';
export { MarketAsset } from './models/MarketAsset';
export type { MarketChange } from './models/MarketChange';
export type { MarketListing } from './models/MarketListing';
export { MarketPaymentMethod } from './models/MarketPaymentMethod';
export type { MarketplaceSearchRequest } from './models/MarketplaceSearchRequest';
export type { MicroDepositCryptoResponse } from './models/MicroDepositCryptoResponse';
export type { MicroServiceChargeRequestFee } from './models/MicroServiceChargeRequestFee';
export type { MobileFeatures } from './models/MobileFeatures';
export type { MobileProcessingDetails } from './models/MobileProcessingDetails';
export type { MobileValidationOptimizations } from './models/MobileValidationOptimizations';
export type { News } from './models/News';
export { NullableOfCloudCartType } from './models/NullableOfCloudCartType';
export { NullableOfMarginModelType } from './models/NullableOfMarginModelType';
export { NullableOfPricingModel } from './models/NullableOfPricingModel';
export { NullableOfVendorType } from './models/NullableOfVendorType';
export type { OrderPaymentAddress } from './models/OrderPaymentAddress';
export { OrderRequestType } from './models/OrderRequestType';
export type { PaymentAddress } from './models/PaymentAddress';
export type { PaymentInfo } from './models/PaymentInfo';
export { PaymentMethod } from './models/PaymentMethod';
export type { PercentageFlux } from './models/PercentageFlux';
export { PercentageFluxTypes } from './models/PercentageFluxTypes';
export type { PortfolioChange } from './models/PortfolioChange';
export type { PortfolioSummary } from './models/PortfolioSummary';
export type { PriceTier } from './models/PriceTier';
export type { PricingStrategy } from './models/PricingStrategy';
export type { ProblemDetails } from './models/ProblemDetails';
export type { PublicTeam } from './models/PublicTeam';
export type { PublicTeamExtendedPrice } from './models/PublicTeamExtendedPrice';
export type { PushNotificationSettings } from './models/PushNotificationSettings';
export type { RefreshTokenRequest } from './models/RefreshTokenRequest';
export type { RemoteTransactionBatchRequest } from './models/RemoteTransactionBatchRequest';
export type { RemoteTransactionBatchResponse } from './models/RemoteTransactionBatchResponse';
export type { RemoteTransactionRequest } from './models/RemoteTransactionRequest';
export type { RemoteTransactionResponse } from './models/RemoteTransactionResponse';
export type { SearchResponse } from './models/SearchResponse';
export type { SearchResult } from './models/SearchResult';
export type { ServiceStatus } from './models/ServiceStatus';
export type { SignupRequest } from './models/SignupRequest';
export type { SignupResponse } from './models/SignupResponse';
export type { SystemStatus } from './models/SystemStatus';
export type { TeamPrice } from './models/TeamPrice';
export type { TokenizedCart } from './models/TokenizedCart';
export type { TokenizedCartItem } from './models/TokenizedCartItem';
export type { Trade } from './models/Trade';
export type { TradingPair } from './models/TradingPair';
export type { TransactionSource } from './models/TransactionSource';
export type { TransferRequest } from './models/TransferRequest';
export type { TransferResponse } from './models/TransferResponse';
export type { UpdateUserRequest } from './models/UpdateUserRequest';
export type { UserCoinMetric } from './models/UserCoinMetric';
export type { UserDetails } from './models/UserDetails';
export type { UserDeviceRegistrationRequest } from './models/UserDeviceRegistrationRequest';
export type { UserDeviceRegistrationResponse } from './models/UserDeviceRegistrationResponse';
export type { UserDeviceSynchronizationRequest } from './models/UserDeviceSynchronizationRequest';
export type { UserDeviceSynchronizationResponse } from './models/UserDeviceSynchronizationResponse';
export type { UserProfile } from './models/UserProfile';
export type { ValidateTokenRequest } from './models/ValidateTokenRequest';
export type { WalletAction } from './models/WalletAction';
export type { WalletActions } from './models/WalletActions';
export type { WalletAsset } from './models/WalletAsset';
export type { WalletAssets } from './models/WalletAssets';
export type { WalletBalance } from './models/WalletBalance';
export type { WalletExtended } from './models/WalletExtended';
export type { WalletExtended2 } from './models/WalletExtended2';
export type { WalletMetadata } from './models/WalletMetadata';
export type { WalletTransaction } from './models/WalletTransaction';
export type { WithdrawRequest } from './models/WithdrawRequest';
export type { WithdrawResponse } from './models/WithdrawResponse';

export { LegacyApIsCloudCartService } from './services/LegacyApIsCloudCartService';
export { LegacyApIsCustomerMarketsService } from './services/LegacyApIsCustomerMarketsService';
export { LegacyApIsDashboardService } from './services/LegacyApIsDashboardService';
export { LegacyApIsGlobalService } from './services/LegacyApIsGlobalService';
export { LegacyApIsMarketsService } from './services/LegacyApIsMarketsService';
export { LegacyApIsSearchService } from './services/LegacyApIsSearchService';
export { LegacyApIsShoppingCartService } from './services/LegacyApIsShoppingCartService';
export { LegacyApIsTokenizedCartService } from './services/LegacyApIsTokenizedCartService';
export { LegacyApIsUsersService } from './services/LegacyApIsUsersService';
export { LegacyApIsWaitingListService } from './services/LegacyApIsWaitingListService';
export { ModernApIsAuthenticationService } from './services/ModernApIsAuthenticationService';
export { ModernApIsCustomerMarketsService } from './services/ModernApIsCustomerMarketsService';
export { ModernApIsDashboardService } from './services/ModernApIsDashboardService';
export { ModernApIsGlobalService } from './services/ModernApIsGlobalService';
export { ModernApIsMarketplaceService } from './services/ModernApIsMarketplaceService';
export { ModernApIsMarketsService } from './services/ModernApIsMarketsService';
export { ModernApIsRemoteTransactionService } from './services/ModernApIsRemoteTransactionService';
export { ModernApIsSearchService } from './services/ModernApIsSearchService';
export { ModernApIsSecondaryMarketsService } from './services/ModernApIsSecondaryMarketsService';
export { ModernApIsTokenizedCartService } from './services/ModernApIsTokenizedCartService';
export { ModernApIsUserManagementService } from './services/ModernApIsUserManagementService';
export { ModernApIsWalletsService } from './services/ModernApIsWalletsService';
export { OtherEndpointsService } from './services/OtherEndpointsService';
export { SystemHealthService } from './services/SystemHealthService';
